name: Event filters and Activity Types

on:
    pull_request:
        types: [opened]
        branches:
            - main
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "PR workflow is working!"
